#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-build-scan-plugin
Version  : 1
Release  : 1
URL      : https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.jar
Source0  : https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.jar
Source1  : https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-build-scan-plugin-data = %{version}-%{release}
Requires: mvn-build-scan-plugin-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-build-scan-plugin package.
Group: Data

%description data
data components for the mvn-build-scan-plugin package.


%package license
Summary: license components for the mvn-build-scan-plugin package.
Group: Default

%description license
license components for the mvn-build-scan-plugin package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-build-scan-plugin
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-build-scan-plugin/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/gradle/build-scan-plugin/2.4.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/gradle/build-scan-plugin/2.4.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.jar
/usr/share/java/.m2/repository/com/gradle/build-scan-plugin/2.4.1/build-scan-plugin-2.4.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-build-scan-plugin/LICENSE
